### ISSUE TITLE
 [INTERNAL] List of rufus-3.19 enhancements and fixes

### ISSUE THREAD

**Issue by pbatard** [pbatard/rufus#1880]
__This topic is flagged as INTERNAL and is therefore NOT open for comments.__

- [x] ~~Add an extra warning message (with countdown until `OK` becomes enabled) if we detected multiple devices and the user didn't select the smaller one. This may avoid people still managing to lose data because they've selected the wrong device.~~ &rarr; Superseded by [c76327f96ebbe0f8c54a4f7dc3cd09b80097838e]
- [x] [e7b66e7e4ce39484e416176b32facd991e62ce61] As [commented](https://github.com/pbatard/rufus/issues/1877#issuecomment-1054643180) in #1877, see if we can switch to delay loading for MinGW to avoid the hassle of manual DLL hooking to prevent side loading
- [x] [8ec570570f36161f241ee0f30d0626e143819855] Revisit the disabling of drive letter assignation to only media that have ESPs (#1842).
- [x] What's the deal with 50% progress before file copy on GRUB2 based ISOs? &rarr; _Nothing &mdash; it's the same as Syslinux based ISOs_
- [x] [a3c75e480ec6b0e21ae63f1a8e02b8ecca9d4ea5] Commit 3194a4dac4c1cff66e812c0fc3375189e0b10d31 is screwing the displaying of the UI for MinGW (whyyyyyyyyy?!?!?) Do we have to revert it?
- [x] [d8af83dd14f10126ad417731b3262f72a3ba051f] Use Linux Data GUID for GPT ext partitions
- [x] [c2cd5185a3f000b92f45156df5bc13334f9769dd] Add Proxmox to the list of _"ISOHybrid = DD"_ Kool Aid drinkers
- [x] [a9a97b6f102a71a9d713821eb889e5e1bb30f870] Secure Boot sign and update UEFI:NTFS's NTFS drivers to latest (and ask Microsoft to revoke previous ones)
- [x] [a0d669232cb3442e54a3e640c3e4009d800183a4] Insert a `BypassNRO` `Autounattend.xml` into `boot.wim` for Windows 11 local account creation, like [`MediaCreationTool.bat` does](https://github.com/AveYo/MediaCreationTool.bat/blob/main/bypass11/AutoUnattend.xml) (and use this opportunity to switch to using the `Autounattend.xml` to alter the WinPE registry hive instead of having to do it ourselves... which should also solve the Windows Store issue we've been seeing in #1884)
- [x] [ae377ae8cafea7a5454d1b1b0b0966bbf1f4b6f4] [Gentoo Live and multiextent with Joliet](https://lists.gnu.org/archive/html/libcdio-devel/2022-06/msg00000.html)
